import assert from 'node:assert/strict';
import {normalizeItem,canonicalKey,mapDepartment,inferZone} from '../scripts/lib/normalize.mjs';
import {dedupeJobs} from '../scripts/lib/dedupe.mjs';
import {updateFreshness} from '../scripts/lib/freshness.mjs';
const src={id:'x',operator:'Test',priority:1,url:'https://example.com'};
assert.equal(mapDepartment('Food and Beverage & Culinary'),'F&B');
assert.equal(mapDepartment('People & Culture'),'Nhân sự');
assert.equal(inferZone('Hon Thom, Phu Quoc'),'Nam đảo');
const a=normalizeItem({sourceJobId:'1',title:'Front Office Manager - Phu Quoc',employer:'Hotel A',location:'Duong To, Phu Quoc',department:'Front Office'},src);
const b=normalizeItem({sourceJobId:'2',title:'Front Office Manager',employer:'Hotel A',location:'Duong To, Phu Quoc',department:'Rooms'},src);
assert.equal(canonicalKey(a),canonicalKey(b));
assert.equal(dedupeJobs([a,b]).length,1);
let state=updateFreshness({},[a],'2026-10-02T00:00:00Z');
assert.equal(state[a.canonicalKey].status,'fresh');
state=updateFreshness(state,[],'2026-10-03T00:00:00Z');
assert.equal(state[a.canonicalKey].status,'needs_recheck');
state=updateFreshness(state,[],'2026-10-04T00:00:00Z');
state=updateFreshness(state,[],'2026-10-05T00:00:00Z');
assert.equal(state[a.canonicalKey].status,'expired');
console.log('PASS pipeline unit tests');
